AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  # The usage of a CMK in the ASG LaunchConfiguration
  # is not supported yet but maybe in the future ?
  # I just leave the code here in case it's supported in the future.
  # Atm. the EBS Volumes are getting encrypted with the key which is
  # provided by the AMIs.
  UseCMKEBSVolumeEncryptionCondition:
    Fn::And:
      - Fn::Equals:
        - Ref: ChaosMonkeyEnableVolEncryptionParameter
        # To support the deprecrated configuration parameters,
        # [aem_component].enable_vol_encryption
        #
        # The new parameter is not support yet.
        # - Fn::Select:
        #   - 0
        #   - Ref: AWSEncryptionParameters
        - true
      - Fn::Not:
          - Fn::Equals:
              - Fn::Select:
                - 1
                - Ref: AWSEncryptionParameters
              - 'overwrite-me'
Description: Create the Compute resources for the AEM Chaos Monkey
Outputs:
  ChaosMonkeyAutoScalingGroup:
    Description: The Chaos Monkey Auto Scaling Group
    Export:
      Name:
        Fn::Sub: ${MainStackPrefixParameter}-ChaosMonkeyAutoScalingGroup
    Value:
      Ref: ChaosMonkeyAutoScalingGroup
  ChaosMonkeyLaunchConfiguration:
    Description: The Chaos Monkey Launch Configuration
    Value:
      Ref: ChaosMonkeyLaunchConfiguration
Parameters:
  AemAwsStackProvisionerVersionParameter:
    Description: AEM AWS Stack Provisioner version number
    Type: String
  AWSEncryptionParameters:
    Description: |
      A list of AWS Encyrption parameters.
      List hast to be containing the following values in the following order:
        - Boolean for enabling/disabling EBS Volume encryption
        - KMS Key ID used for EBS Volume encryption
    Type: List<String>
  ChaosMonkeyASGAvailabilityZoneListParameter:
    Description: The Chaos Monkey Availability Zone List
    Type: List<AWS::EC2::AvailabilityZone::Name>
  ChaosMonkeyImageParameter:
    Description: The Chaos Monkey Image Id
    Type: AWS::EC2::Image::Id
  ChaosMonkeyImageRootDevice:
    Default: /dev/sda1
    Description: The root device name for the Chaos Monkey Image Id
    Type: String
  ChaosMonkeyInstanceTypeParameter:
    Description: The Chaos Monkey Instance Type
    Type: String
  ChaosMonkeyRootVolSizeParameter:
    Description: Chaos Monkey Instances Root EBS Volum Size
    Type: Number
  ChaosMonkeyEnableVolEncryptionParameter:
    AllowedValues:
    - true
    - false
    Description: Wether to enable or disable EBS volume encryption.
    Type: String
  ComputeKeyPairNameParameter:
    Description: The Compute Resources Key Pair Name
    Type: AWS::EC2::KeyPair::KeyName
  DataBucketNameParameter:
    Description: Bucket name that stores Stack data files
    Type: String
  MainStackPrefixParameter:
    Description: The AEM Stack Compute Resources Stack Prefix
    Type: String
  NetworkStackPrefixParameter:
    Description: The AEM Stack Network Resources Stack Prefix
    Type: String
  PrerequisitesStackPrefixParameter:
    Description: The AEM Stack Prerequisite Resources Stack Prefix
    Type: String
Resources:
  ChaosMonkeyAutoScalingGroup:
    Properties:
      AvailabilityZones:
        Ref: ChaosMonkeyASGAvailabilityZoneListParameter
      HealthCheckGracePeriod: 300
      HealthCheckType: EC2
      LaunchConfigurationName:
        Ref: ChaosMonkeyLaunchConfiguration
      MaxSize: 1
      MetricsCollection:
      - Granularity: 1Minute
        Metrics:
        - GroupMinSize
        - GroupMaxSize
        - GroupDesiredCapacity
        - GroupInServiceInstances
        - GroupPendingInstances
        - GroupStandbyInstances
        - GroupTerminatingInstances
        - GroupTotalInstances
      MinSize: 1
      Tags:
      - Key: Name
        PropagateAtLaunch: true
        Value: AEM Chaos Monkey
      - Key: StackPrefix
        PropagateAtLaunch: true
        Value:
          Ref: MainStackPrefixParameter
      - Key: Component
        PropagateAtLaunch: true
        Value: chaos-monkey
      - Key: OrchestratorASG
        PropagateAtLaunch: true
        Value:
          Fn::ImportValue:
            Fn::Sub: ${MainStackPrefixParameter}-OrchestratorAutoScalingGroup
      - Key: PublisherASG
        PropagateAtLaunch: true
        Value:
          Fn::ImportValue:
            Fn::Sub: ${MainStackPrefixParameter}-PublishAutoScalingGroup
      - Key: PublisherDispatcherASG
        PropagateAtLaunch: true
        Value:
          Fn::ImportValue:
            Fn::Sub: ${MainStackPrefixParameter}-PublishDispatcherAutoScalingGroup
      - Key: AuthorDispatcherASG
        PropagateAtLaunch: true
        Value:
          Fn::ImportValue:
            Fn::Sub: ${MainStackPrefixParameter}-AuthorDispatcherAutoScalingGroup
      VPCZoneIdentifier:
        Fn::Split:
        - ','
        - Fn::ImportValue:
            Fn::Sub: ${NetworkStackPrefixParameter}-ChaosMonkeySubnetList
    Type: AWS::AutoScaling::AutoScalingGroup
  ChaosMonkeyLaunchConfiguration:
    Properties:
      AssociatePublicIpAddress: false
      BlockDeviceMappings:
      - DeviceName:
          Ref: ChaosMonkeyImageRootDevice
        Ebs:
          DeleteOnTermination: true
          Encrypted:
            Ref: ChaosMonkeyEnableVolEncryptionParameter
            # To support the deprecrated configuration parameters,
            # [aem_component].enable_vol_encryption
            #
            # The new parameter is not support yet.
            # Fn::Select:
            #   - 0
            #   - Ref: AWSEncryptionParameters
          # KmsKeyId:
          #     Fn::If:
          #     - UseCMKEBSVolumeEncryptionCondition
          #     - Fn::Select:
          #         - 1
          #         - Ref: AWSEncryptionParameters
          #     - Ref: AWS::NoValue
          VolumeSize:
            Ref: ChaosMonkeyRootVolSizeParameter
          VolumeType: gp2
      IamInstanceProfile:
        Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-ChaosMonkeyInstanceProfile
      ImageId:
        Ref: ChaosMonkeyImageParameter
      InstanceMonitoring: false
      InstanceType:
        Ref: ChaosMonkeyInstanceTypeParameter
      KeyName:
        Ref: ComputeKeyPairNameParameter
      SecurityGroups:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-ChaosMonkeySecurityGroup
      UserData:
        Fn::Base64:
          Fn::Sub: "#!/bin/bash -x\n source /etc/profile\n mkdir -p /opt/shinesolutions/aem-aws-stack-builder/\n\
            \ aws s3 cp s3://${DataBucketNameParameter}/${MainStackPrefixParameter}/stack-init.sh\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n chmod 755\
            \ /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\n /opt/shinesolutions/aem-aws-stack-builder/stack-init.sh\
            \ ${DataBucketNameParameter} ${MainStackPrefixParameter} chaos-monkey\
            \ ${AemAwsStackProvisionerVersionParameter}\n"
    Type: AWS::AutoScaling::LaunchConfiguration
  WarningChaosMonkeyNoInstanceAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-WarningAlarmNotificationTopic
      AlarmDescription: No Chaos Monkey Instance in Service
      AlarmName:
        Fn::Sub: ${MainStackPrefixParameter}-Warning-ChaosMonkey-NoInstanceAlarm
      ComparisonOperator: LessThanThreshold
      Dimensions:
      - Name: AutoScalingGroupName
        Value:
          Ref: ChaosMonkeyAutoScalingGroup
      EvaluationPeriods: 5
      MetricName: GroupInServiceInstances
      Namespace: AWS/AutoScaling
      OKActions:
      - Fn::ImportValue:
          Fn::Sub: ${PrerequisitesStackPrefixParameter}-WarningAlarmNotificationTopic
      Period: 60
      Statistic: Average
      Threshold: 1
    Type: AWS::CloudWatch::Alarm

  WarningChaosMonkeyMemoryHighAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-WarningAlarmNotificationTopic
      AlarmDescription: Memory Utilization is high
      AlarmName:
        Fn::Sub:
          - "${MainStackPrefixParameter}-Warning-ChaosMonkey-MemoryHighAlarm"
          - MainStackPrefixParameter:
              Ref: 'MainStackPrefixParameter'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: "AutoScalingGroupName"
          Value:
            Ref: ChaosMonkeyAutoScalingGroup
      EvaluationPeriods: 1
      MetricName: MemoryUtilization
      Namespace: "System/Linux"
      OKActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-WarningAlarmNotificationTopic
      Period: 300
      Statistic: Average
      Threshold: 80
    Type: AWS::CloudWatch::Alarm
  CriticalChaosMonkeyMemoryHighAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-CriticalAlarmNotificationTopic
      AlarmDescription: Memory Utilization is high
      AlarmName:
        Fn::Sub:
          - "${MainStackPrefixParameter}-Critical-ChaosMonkey-MemoryHighAlarm"
          - MainStackPrefixParameter:
              Ref: 'MainStackPrefixParameter'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: "AutoScalingGroupName"
          Value:
            Ref: ChaosMonkeyAutoScalingGroup
      EvaluationPeriods: 1
      MetricName: MemoryUtilization
      Namespace: "System/Linux"
      OKActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-CriticalAlarmNotificationTopic
      Period: 300
      Statistic: Average
      Threshold: 90
    Type: AWS::CloudWatch::Alarm
  WarningChaosMonkeyRootDiskSpaceUtilizationAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-WarningAlarmNotificationTopic
      AlarmDescription: Disk Space Utilization is high
      AlarmName:
        Fn::Sub:
          - "${MainStackPrefixParameter}-Warning-ChaosMonkey-RootDiskSpaceHighAlarm"
          - MainStackPrefixParameter:
              Ref: 'MainStackPrefixParameter'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: "AutoScalingGroupName"
          Value:
            Ref: ChaosMonkeyAutoScalingGroup
        - Name: MountPath
          Value: "/"
        - Name: Filesystem
          Value: "/"
      EvaluationPeriods: 1
      MetricName: DiskSpaceUtilization
      Namespace: "System/Linux"
      OKActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-WarningAlarmNotificationTopic
      Period: 300
      Statistic: Average
      Threshold: 80
    Type: AWS::CloudWatch::Alarm
  CriticalChaosMonkeyRootDiskSpaceUtilizationAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-CriticalAlarmNotificationTopic
      AlarmDescription: Disk Space Utilization is high
      AlarmName:
        Fn::Sub:
          - "${MainStackPrefixParameter}-Critical-ChaosMonkey-RootDiskSpaceHighAlarm"
          - MainStackPrefixParameter:
              Ref: 'MainStackPrefixParameter'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: "AutoScalingGroupName"
          Value:
            Ref: ChaosMonkeyAutoScalingGroup
        - Name: MountPath
          Value: "/"
        - Name: Filesystem
          Value: "/"
      EvaluationPeriods: 1
      MetricName: DiskSpaceUtilization
      Namespace: "System/Linux"
      OKActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-CriticalAlarmNotificationTopic
      Period: 300
      Statistic: Average
      Threshold: 90
    Type: AWS::CloudWatch::Alarm
  WarningChaosMonkeyCPUUtilizationAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-WarningAlarmNotificationTopic
      AlarmDescription: CPU Utilization is high
      AlarmName:
        Fn::Sub:
          - "${MainStackPrefixParameter}-Warning-ChaosMonkey-CPUHighAlarm"
          - MainStackPrefixParameter:
              Ref: 'MainStackPrefixParameter'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: "AutoScalingGroupName"
          Value:
            Ref: ChaosMonkeyAutoScalingGroup
      EvaluationPeriods: 1
      MetricName: CPUUtilization
      Namespace: "AWS/EC2"
      OKActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-WarningAlarmNotificationTopic
      Period: 300
      Statistic: Maximum
      Threshold: 60
    Type: AWS::CloudWatch::Alarm
  CriticalChaosMonkeyCPUUtilizationAlarm:
    Properties:
      ActionsEnabled: true
      AlarmActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-CriticalAlarmNotificationTopic
      AlarmDescription: CPU Utilization is high
      AlarmName:
        Fn::Sub:
          - "${MainStackPrefixParameter}-Critical-ChaosMonkey-CPUHighAlarm"
          - MainStackPrefixParameter:
              Ref: 'MainStackPrefixParameter'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: "AutoScalingGroupName"
          Value:
            Ref: ChaosMonkeyAutoScalingGroup
      EvaluationPeriods: 1
      MetricName: CPUUtilization
      Namespace: "AWS/EC2"
      OKActions:
        - Fn::ImportValue:
            Fn::Sub: ${PrerequisitesStackPrefixParameter}-CriticalAlarmNotificationTopic
      Period: 300
      Statistic: Maximum
      Threshold: 90
    Type: AWS::CloudWatch::Alarm
